### ISSUE TITLE
Devrant++ price difference on app vs store

### ISSUE THREAD

**Issue by KushtrimPacaj** [devRant/devRant#232]
![b3d315f3-e0b6-4d5a-93f8-45a4a1129fa1](https://user-images.githubusercontent.com/8522712/32406910-c03274b8-c180-11e7-9070-80c30975868c.png)

![61bedf96-5395-4ac1-85c4-7bbe3f7abb68](https://user-images.githubusercontent.com/8522712/32406931-027e88de-c181-11e7-8f54-f76584aa4868.png)

**Comment by DFoxinator** [comment]
What country did you purchase from?

Likely this is just an unavoidable tax, based on country, that Apple adds on to any purchase price. If you look at the receipt you receive from Apple, they should tell you.

What's odd is, looking at my subscriptions on iOS, it just shows $1.99 but when I receive the receipt about $0.17 of tax is included. Not sure why it's different in this case.

**Comment by KushtrimPacaj** [comment]
Albanian app store.

Alright, if it's a tax then there's nothing to do. I thought you just had forgotten to update the value in the app, that's why I reported this :)

**Comment by DFoxinator** [comment]
@KushtrimPacaj thanks - yeah we've never changed the price since launch. The way it works with Apple is they don't even let you set the price. We just select the price tier (which we set to $1.99 USD) and they automatically set it for every country. To be honest, I'm not exactly sure how they even decide. I think the taxes are baked in there, or there's something with exchange rates, but I'm not entirely sure how that works :)

**Comment by cozyplanes** [comment]
As my knowledge goes, dev selects price tier in dev centre, and apple puts appropriate tax in the selected tier. Those price differences isn't controllable by the app dev.

**Comment by KushtrimPacaj** [comment]
Indeed, I received the invoice in the email a few days after, and it has $0.40 tax
![image](https://user-images.githubusercontent.com/8522712/33239253-2cef2cc6-d29e-11e7-81b0-985cec00c540.png)
