### ISSUE TITLE
[API] Include favorites and subscribed in rants/comments

### ISSUE THREAD

**Issue by tahnik** [devRant/devRant#29]
Not sure if this is possible, but if a user is logged in, it would be nice to add a field in the response of the comments or rants saying if it's Original Poster is subscribed by the logged in user. Same goes for favourites. It will be easy to show in the UI if a particular rant was favourited by the user. Or if a user has already subscribed to the poster of a rant.

**Comment by DFoxinator** [comment]
When fetching a rant, if the user is logged in, the API will return a property with the result called "subscribed" if the user is subscribed to the owner of the rant. That property is on the top level result. If the user has favorited that rant, then there will be a property "favorited" set to 1 on the rant info itself within the result.

Are those what you're looking for?

**Comment by tahnik** [comment]
Ah, so those fields only exist when it's necessary. Thanks.

**Comment by tahnik** [comment]
Sorry to reopen this one, but I don't see any "subscribed" field in the rants or profile. Am I missing something?

**Comment by DFoxinator** [comment]
@tahnik subscribed should definitely be there for the API requests for both an individual rant and a profile, both specifying that the user is subscribed to that specific person (or the creator of that rant).

It may only show as subscribed=1 if you are subscribed, and might not be there otherwise. Please let me know if you still don't see it.

**Comment by DFoxinator** [comment]
This should exist, so closing.
