### ISSUE TITLE
[Feature Request]: Ban status checks

### ISSUE THREAD

**Issue by roryphillipsdeveloper** [devRant/devRant#299]
As I learned in the comment thread on this rant

https://devrant.com/rants/1134376/is-there-a-thing-like-getting-shadowbanned-from-downvoting-on-devrant-or-people

Users can get downvote banned.
I am unsure of any systems that may be in place as I have not encountered them, but is it possible to be informed of a ban that has been placed on your account when it has been placed.

Warnings when you are nearing the point where you will get banned, and perhaps a small summary on the about page as to what sort of behaviour would warrant getting warnings / bans would also be very helpful.

**Comment by cozyplanes** [comment]
When you downvote literally every rant, or a specific user's rant, the admin can notice it and may ban you from downvoting more.

**Comment by DFoxinator** [comment]
This isn't really the kind of thing that warrants warnings and more information in my opinion. If you get downvote banned it literally has pretty much 0 impact on your devRant experience. I don't see it as a privilege people need to have to be able to mark things as offensive/spam. And you only ever get downvote banned if you're caught marking something as "offensive/spam" that blatantly wasn't.

But beyond that, I see it as counter-productive to provide more information to people because we don't want downvote abusers to be able to obviously know when their offensive/spam votes aren't being counted in scores anymore.
