### ISSUE TITLE
[Feature-Request] Webapp - report missing

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#340]
There is no report option currently in the new webapp.

**Comment by xlf1024** [comment]
There is, it's accessible through the downvote.

**Comment by Skayo** [comment]
@xlf1024 It's not what he meant. He meant the standalone report button. What you mean is just downvote

**Comment by xlf1024** [comment]
@Skayo I get that, but the options "Repost" and "Offensive/Spam" sound like they're actually reporting the rant.

**Comment by DFoxinator** [comment]
I'm going to close this - while the actual "report" button is missing, we have no intention of adding it as downvote as spam/offensive is more or less the same thing and that and/or tagging me is the best option. We are required to have the report buttons on mobile because of Apple App Store rules (and Goolge Play?)
