### ISSUE TITLE
Rant feed in webapp does not cut off long rants

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#353]
If you're on desktop long rants don't seem to get cut off like on mobile with "[read more]"

**Comment by xlf1024** [comment]
I quite enjoy it the way it is.

**Comment by DFoxinator** [comment]
@trogus do you think we should cut it off on web?

**Comment by toloveru** [comment]
This is also the case in devRantron. I actually quite like it, saves some navigation and allows you to read the whole rant straight from the feed. On mobile it makes sense to cut them off because small screen, lower performance (possibly), undesirable network conditions etc etc. On desktop however, even the long rants don't take up that much screen real estate and network conditions are usually good. Personally I'd like to keep it the way it is, or a toggle to be added in the settings perhaps.

**Comment by trogus** [comment]
Plenty of space, might as leave fully displayed (I thought we were doing
this already)

**Comment by 7twin** [comment]
Seeing it that way, I agree, leaving them fully displayed can save some navigation on desktop
