### ISSUE TITLE
[Heisenbug] often downvoting doesn't cause the post score to decrease

### ISSUE THREAD

**Issue by toloveru** [devRant/devRant#405]
It's not very often that I downvote content, but when I do it's often not properly registered. Very annoying because getting the post score down is - to me at least - the primary purpose of downvoting.

I wish that I could be more specific other than that I recently downvoted a couple of things from the -life accounts, and that it sometimes gets registered properly while often it doesn't. But it occurs seemingly at random.

**Comment by 7twin** [comment]
See #387 for how the downvote function is supposed to be used

**Comment by toloveru** [comment]
I know what the downvote feature is used for, hence why I don't use it very often. This issue however is on the score reflection whenever such a downvote occurs, and therefore unrelated to the intents behind it.

**Comment by 7twin** [comment]
It's not reflected in the users score, if it's not marked as spam, but also if you abuse said function, you'll get downvote banned by the system.

**Comment by toloveru** [comment]
Okay, so downvoting the content of clearly abusive users (which by the way have all been banned afterwards because yeah their content was degenerative to the community at large) causes the system to flag the flagger. Got it.

**Comment by 7twin** [comment]
@toloveru only if there's clear abuse of said function (to downvote any user, instead of using it only for actual spam), dfox didn't want to say how it determines it, for obvious reasons though, but be sure if you mark a lot of spam, you'll probably get downvote banned and none of the options will anymore be logged serverside and go towards the user score.

**Comment by DFoxinator** [comment]
@toloveru it pretty much works exactly how @7twin said. Also, I looked you up - you're not even downvote banned, so "downvoting the content of clearly abusive users causes the system to flag the flagger" certainly isn't accurate and the accurate version also doesn't apply to you since you're not downvote banned. So I'm not really sure what you're asking. When you downvote as offensive/spam, the rant loses a point and so does the user, and you'll see that reflected in the score...

We also don't "flag the flagger" for people who legitimately mark offensive/spam content. And it's hardly an automated process for those who are banned. We have abuse measures for people who are engaging in too much spam/offensive downvoting (but that's when you do it a lot), and the rest is manual. Meaning, I see a rant/comment that shouldn't be downvoted as offensive/spam, and I can tell the system to downvote ban all the users who marked the rant/comment as offensive/spam.

So I'm not sure if there's an actual issue/bug/report here. It seems like everything is functioning as expected, unless you're downvoting as offensive/spam and not seeing anything happening. If that's the case, please re-open this.

**Comment by toloveru** [comment]
Thanks for the clarification. Having a system to protect from downvote abuse makes sense.

I've uploaded some screenshots to reflect the state of this issue. This particular piece of content was downvoted with the reason being "not for me". I've undone the downvote by now because it seems to be little more than disagreement in that case. But you can test this by downvoting something and seeing the post score not change when you refresh the post.

https://imgur.com/a/R2aREK4

**Comment by 7twin** [comment]
@toloveru that's how the system is supposed to work, anything else that isn't spam, will only clientside downvote, but if you refresh, not actually be saved to the server, since users and their scores don't get punished for e.g. "not for me"

**Comment by DFoxinator** [comment]
"Not for me" downvotes are saved on the server, and are used for your personal recommendations in algo feed view. But they can be used as much as you want on anything, with no penalty. That's why it's called "not for me" - it's personal opinion and meant to be used whenever you want it. Offensive/spam is reserved for content that breaks our rules, hence why it impacts the score of the rant and user's score.

**Comment by 7twin** [comment]
@DFoxinator Oh yeah, I think I asked this before, but why are those saved, I don't think there is any comment filters planned nor implemented like with rants, where the "not for me" is weighed into the algo?

**Comment by toloveru** [comment]
It seems that while downvote as "offensive/spam" does decrease post score, the options "not for me", and "repost" don't. Based on the explanations so far, this seems like it's indeed the intended behavior.

I'd say that this issue is solved. Thanks for the clarification 🙂
