### ISSUE TITLE
Add xmlRant.com to the projects page ;)

### ISSUE THREAD

**Issue by olegrumiancev** [devRant/devRant#89]
Hi there, just a reminder issue to add http://xmlRant.com to projects page ;)

**Comment by Skayo** [comment]
Please read the text on the projects page:
“If you have a project you built on the devRant platform that's missing from here, please email info@devrant.io and we will add it!“

**Comment by cozyplanes** [comment]
@DFoxinator

**Comment by DFoxinator** [comment]
@Skayo that text is old and will be changed. This is how we're going to do it going forward.

**Comment by olegrumiancev** [comment]
Also, a nuget package for .net core API wrapper https://www.nuget.org/packages/devRantNetCore 
Will try to sort out github repos a bit later and share as well...

**Comment by olegrumiancev** [comment]
@DFoxinator @trogus  am I ok to try to implement log in mechanism and subsequently enabling comments?

**Comment by DFoxinator** [comment]
@olegrumiancev first off apologies for the delay. I've been very busy with a bunch of devRant-related things and just got around to updating the projects page now. xmlRant has been added and we really appreciate your hard work on it. It's looking awesome! Let me know if there's any changes to the description you'd like, I pretty much used the jsRant description as a base.

I also missed your question the first time around - we've tried to ask the community to stay away from hosted projects (like websites) that use login functionality because we don't have a good oauth-like system yet and we only allow username and password right now, so there's kind of a security issue with that. We do plan to add a third-party app login system API though in the not too distant future.

Please let me know if you have any other questions and thanks again, xmlRant is really awesome and I'm sorry it took so long to get it on the project page.

**Comment by olegrumiancev** [comment]
@DFoxinator thanks mate! It's no problem at all re delay - I just look at the expanding issue tracker and totally understand ;) Keep up the great work.
